const response = {
  SERVER_ERROR_MESSAGE: "server error!",
  DATA_NOT_FOUND_MESSAGE: "data not found!",
  EMAIL_ALREADY_EXIST_MESSAGE: "email already exist!",
  REGISTRATION_SUCCESS_MESSAGE: "registration successful",
  INCORRECT_PASSWORD_MESSAGE: "incorrect password",
  LOGIN_SUCCESSFUL_MESSAGE: "login successful",
  UPDATE_SUCCESS_MESSAGE: "update successful",
  OTP_SEND_SUCCESS_MESSAGE: "otp send successful",
  TOKEN_EXPIRED_MESSAGE: "token expired",
  OTP_MATCH_SUCCESS_MESSAGE: "otp matched",
  OTP_NOT_MATCH_MESSAGE: "otp does not match",
  PASSWORD_CHANGE_SUCCESS_MESSAGE: "password changed successful",
  DELETE_SUCCESS_MESSAGE: "account delete successful",
  USERNAME_ALREADY_EXIST_MESSAGE: "username already exist",
  REGISTRATION_VERIFY_OTP_MESSAGE:
    "registration successful, please check your email",
  ALREADY_VERIFY_MESSAGE: "already verified",
  VERIFICATION_SUCCESS_MESSAGE: "verification successful",
  ENTER_WRONG_CODE_MESSAGE: "enter wrong code",
  VERIFY_YOUR_ACCOUNT_MESSAGE: "please verify your account",
  ACCOUNT_CREATE_SUCCESS_MESSAGE: "account created successful",
  LINK_SEND_SUCCESS_MESSAGE: "link send successful",
  NOT_ELIGABLE_FOR_BID_MESSAGE: "bidding are not available",
  ALREADY_SEND_MESSAGE: "you have already send message",
  MESSAGE_SEND_MESSAGE: "message sent",
  COMMUNICATION_MARK_SEEN_MESSAGE: "communications marked as seen",
  COMMUNICATION_NOT_FOUND_MESSAGE: "communication not found!",
  CREDIT_CREATE_SUCCESS_MESSAGE: "credit create successful",
  CREDIT_CANCEL_SUCCESS_MESSAGE: "credit cancel successful",
  CREDIT_NOT_FOUND_MESSAGE: "credits not found!",
  JOB_PENDING_VERIFY_REQUIRE_MESSAGE:
    "job is pending, please verify your email",
  JOB_CREATE_SUCCESS_MESSAGE: "job created successful",
  MEMBERSHIP_CREATE_SUCCESS_MESSAGE: "membership create successful",
  MEMBERSHIP_CANCEL_SUCCESS_MESSAGE: "membership cancel successful",
  CREATE_NEWS_SUCCESS_MESSAGE: "news create successful",
  BID_NOT_ACCEPT_MESSAGE: "no more bid are accepted",
  PARTICIPATION_SUCCESS_MESSAGE: "perticipation successful",
  ENOUGH_CREDIT_REQUIRE_MESSAGE: "you do not have enough credits",
  REQUEST_SEND_SUCCESS_MESSAGE: "request send successful",
  NOT_ELIGABLE_TO_SEND_BID_RESPONSE: "you are not eligble to send bid",
  ALREADY_SEND_BID_MESSAGE: "you are already send bid",
  BID_SEND_SUCCESS_MESSAGE: "bid send successful",
  ALREADY_SEND_REQUEST_MESSAGE: "already send a request",
  SELLER_NOT_HAVE_ENOUGH_CREDIT_MESSAGE: "seller does not have enough credit",
  REVIEW_REQUEST_SEND_MESSAGE: "review request send",
  OFFER_ARCHIVED_SUCCESS_MESSAGE: "offer archived successful",
  MEMBERSHIP_ALREADY_CREATE_MESSAGE: "membership already created",
  WEBOOK_CONNECTED_SUCCESS_MESSAGE: "webhook connected successful",
  ALREADY_SAVE_JOB_MESSAGE: "you have already save this job",
  JOB_SAVE_SUCCESS_MESSAGE: "job saved successful",
  REVIEW_ALREADY_SUBMIT_MESSAGE: "review already submited",
  REVIEW_SUBMIT_SUCCESS_MESSAGE: "review submited successful",
  YOU_HAVE_ALREADY_LIKE_MESSAGE: "you have already liked",
  LIKED_SUCCESS_MESSAGE: "liked successful",
  ID_REQUIRED_ERROR_MESSAGE: "id is required",
  UID_ALREADY_EXIST_MESSAGE: "uid already exist",
  INVALID_TOEKN_MESSAGE: "invalid token or seller not found!",
  EMAIL_VERIFICATOPM_SUCCESS_MESSAGE: "email verified successfully",
  SELLER_EMAIL_NOT_VERIFYED_MESSAGE: "seller email not verifyed",
  PLEASE_VERIFY_EMAIL_UID_MESSAGE: "please verify email and uid",
  ACTIVITY_SAVED_MESSAGE: "activity saved",
  UNAUTHORIZE_USER_MESSAGE: "unauthorize user",
  CORS_ERROR_MESSAGE: "not allowed by cors",
  ROUTE_NOT_FOUND_MESSAGE: "route not found!",
  HOME_ROUTE_MESSAGE: "home route",
  INVALID_PLAN_MESSAGE: "Invalid plan selected",
};

module.exports = response;
